export const LECTURE_FETCH_LECTURE_BEGIN = 'LECTURE_FETCH_LECTURE_BEGIN';
export const LECTURE_FETCH_LECTURE_SUCCESS = 'LECTURE_FETCH_LECTURE_SUCCESS';
export const LECTURE_FETCH_LECTURE_FAILURE = 'LECTURE_FETCH_LECTURE_FAILURE';
export const LECTURE_FETCH_LECTURE_RESET = 'LECTURE_FETCH_LECTURE_RESET';

export const LECTURE_FETCH_SCHOOL_BEGIN = 'LECTURE_FETCH_SCHOOL_BEGIN';
export const LECTURE_FETCH_SCHOOL_SUCCESS = 'LECTURE_FETCH_SCHOOL_SUCCESS';
export const LECTURE_FETCH_SCHOOL_FAILURE = 'LECTURE_FETCH_SCHOOL_FAILURE';
export const LECTURE_FETCH_SCHOOL_RESET = 'LECTURE_FETCH_SCHOOL_RESET';

export const LECTURE_FETCH_MAJOR_BEGIN = 'LECTURE_FETCH_MAJOR_BEGIN';
export const LECTURE_FETCH_MAJOR_SUCCESS = 'LECTURE_FETCH_MAJOR_SUCCESS';
export const LECTURE_FETCH_MAJOR_FAILURE = 'LECTURE_FETCH_MAJOR_FAILURE';
export const LECTURE_FETCH_MAJOR_RESET = 'LECTURE_FETCH_MAJOR_RESET';
