export const SCHEDULE_FETCH_ITEM_BEGIN = 'SCHEDULE_FETCH_ITEM_BEGIN';
export const SCHEDULE_FETCH_ITEM_SUCCESS = 'SCHEDULE_FETCH_ITEM_SUCCESS';
export const SCHEDULE_FETCH_ITEM_FAILURE = 'SCHEDULE_FETCH_ITEM_FAILURE';

export const SCHEDULE_CREATE_TASK_BEGIN = 'SCHEDULE_CREATE_TASK_BEGIN';
export const SCHEDULE_CREATE_TASK_SUCCESS = 'SCHEDULE_CREATE_TASK_SUCCESS';
export const SCHEDULE_CREATE_TASK_FAILURE = 'SCHEDULE_CREATE_TASK_FAILURE';
