export const SCHEDULE_FETCH_ITEM_BEGIN = 'SCHEDULE_FETCH_ITEM_BEGIN';
export const SCHEDULE_FETCH_ITEM_SUCCESS = 'SCHEDULE_FETCH_ITEM_SUCCESS';
export const SCHEDULE_FETCH_ITEM_FAILURE = 'SCHEDULE_FETCH_ITEM_FAILURE';

export const SCHEDULE_CREATE_TASK_BEGIN = 'SCHEDULE_CREATE_TASK_BEGIN';
export const SCHEDULE_CREATE_TASK_SUCCESS = 'SCHEDULE_CREATE_TASK_SUCCESS';
export const SCHEDULE_CREATE_TASK_FAILURE = 'SCHEDULE_CREATE_TASK_FAILURE';

export const SCHEDULE_REMOVE_TASK_BEGIN = 'SCHEDULE_REMOVE_TASK_BEGIN';
export const SCHEDULE_REMOVE_TASK_SUCCESS = 'SCHEDULE_REMOVE_TASK_SUCCESS';
export const SCHEDULE_REMOVE_TASK_FAILURE = 'SCHEDULE_REMOVE_TASK_FAILURE';

export const SCHEDULE_FETCH_TAG_BEGIN = 'SCHEDULE_FETCH_TAG_BEGIN';
export const SCHEDULE_FETCH_TAG_SUCCESS = 'SCHEDULE_FETCH_TAG_SUCCESS';
export const SCHEDULE_FETCH_TAG_FAILURE = 'SCHEDULE_FETCH_TAG_FAILURE';

export const SCHEDULE_ADD_LECTURE_BEGIN = 'SCHEDULE_ADD_LECTURE_BEGIN';
export const SCHEDULE_ADD_LECTURE_SUCCESS = 'SCHEDULE_ADD_LECTURE_SUCCESS';
export const SCHEDULE_ADD_LECTURE_FAILURE = 'SCHEDULE_ADD_LECTURE_FAILURE';
